remove mapping to trigger field
elastic/elastic-package pull request #1245
Opened 2023-04-28 09:13 UTC by gsantoro

Since we removed the field `faas.trigger` with type nested from ECS definition with this issue https://github.com/elastic/ecs/issues/2192, we also want to remove the dynamic mapping definition.

2023-04-28 09:45 UTC, felixbarny approved these changes

2023-04-28 09:48 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/elastic-package/builds/688)
* Commit: dc9b36be19bc3594e5e5c12f98e8a73b3b446d96

### Failed CI Steps
* [:go: Running integration test: nginx](https://buildkite.com/elastic/elastic-package/builds/688#0187c73d-e9cc-4938-89d9-d4744f0ca9c7)

<!--buildkite-pr-comment-elastic-package
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-package/builds/688","number":688,"commit":"dc9b36be19bc3594e5e5c12f98e8a73b3b446d96"}],"number":688}
buildkite-pr-comment-->

2023-04-28 09:53 UTC, mrodm commented on internal/builder/testdata/existing.yml
> -              type: nested
If this needs to be removed, please add another one. This file is to be used in a test that ensures that dynamic mappings are added without removing the ones defined in this section.

2023-04-28 13:29 UTC, mrodm requested changes
Add some element into `dynamic_templates` in the `internal/builder/testdata/existing.yml` file

2023-04-28 15:11 UTC, elasticmachine commented
## :hourglass_flowing_sand: Build in-progress, with failures
* [Buildkite Build](https://buildkite.com/elastic/elastic-package/builds/689)
* Commit: 260ed7a65c99de712567eb39dafe6c6d723246f1

### Failed CI Steps
* [:go: :linux: Run unit tests](https://buildkite.com/elastic/elastic-package/builds/689#0187c869-45ba-493e-9cb4-99721898b44d)

### History
* :broken_heart: [Build #688](https://buildkite.com/elastic/elastic-package/builds/688) failed dc9b36be19bc3594e5e5c12f98e8a73b3b446d96

<!--buildkite-pr-comment-elastic-package
{"builds":[{"buildStatus":{"state":"failing","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-package/builds/689","number":689,"commit":"260ed7a65c99de712567eb39dafe6c6d723246f1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-package/builds/688","number":688,"commit":"dc9b36be19bc3594e5e5c12f98e8a73b3b446d96"}],"number":689}
buildkite-pr-comment-->

2023-04-28 16:33 UTC, jsoriano commented on internal/builder/testdata/existing.yml
> +                type: ip
I think CI complains about some extra space here.
```suggestion
              type: ip
```

2023-04-28 16:33 UTC, jsoriano commented on internal/builder/testdata/expected.existing.mappings.yml
> +                type: ip
And/or here.
```suggestion
              type: ip
```

2023-05-02 09:43 UTC, elasticmachine commented
## :green_heart: Build Succeeded
* [Buildkite Build](https://buildkite.com/elastic/elastic-package/builds/694)
* Commit: 6de904b526e592522288df5ef628af4510aa8d77

### History
* :broken_heart: [Build #689](https://buildkite.com/elastic/elastic-package/builds/689) failed 260ed7a65c99de712567eb39dafe6c6d723246f1
* :broken_heart: [Build #688](https://buildkite.com/elastic/elastic-package/builds/688) failed dc9b36be19bc3594e5e5c12f98e8a73b3b446d96

<!--buildkite-pr-comment-elastic-package
{"builds":[{"buildStatus":{"state":"passed","success":true,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-package/builds/694","number":694,"commit":"6de904b526e592522288df5ef628af4510aa8d77"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-package/builds/689","number":689,"commit":"260ed7a65c99de712567eb39dafe6c6d723246f1"},{"buildStatus":{"state":"failed","success":false,"hasRetries":false,"hasNonPreemptionRetries":false},"url":"https://buildkite.com/elastic/elastic-package/builds/688","number":688,"commit":"dc9b36be19bc3594e5e5c12f98e8a73b3b446d96"}],"number":694}
buildkite-pr-comment-->

2023-05-02 13:35 UTC, mrodm approved these changes
Thanks! LGTM!

2023-05-02 14:37 UTC, merged