Deploy agent with hostNetwork on k8s
elastic/elastic-package pull request #332
Opened 2021-04-20 14:16 UTC by ChrsMark

We need to deploy Agent using `hostNetwork` option so as to have access to node's ports directly for testing endpoints like these of scheduler's and controllermanager.

2021-04-20 14:39 UTC, mtojek approved these changes
WFG

2021-04-20 14:40 UTC, mtojek commented
BTW To verify features introduced in PRs you can use the `test/packages` stuff to quickly write up samples. In this case you could verify the connectivity (not required, just a hint).

2021-04-20 14:52 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package%2FPR-332/detail/PR-332/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package%2FPR-332/detail/PR-332/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package%2FPR-332/detail/PR-332/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package%2FPR-332/detail/PR-332/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-package_332.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #332 opened`



* Start Time: 2021-04-20T14:16:24.902+0000


* Duration: 36 min 49 sec


* Commit: 31be27602e28a2971af86b978612922cf3f4f49f



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 273  |
| Skipped      | 1 |
| Total        | 274   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-332/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-332/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->









### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package%2FPR-332/detail/PR-332/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Check`
<ul>
<li>Took 22 min 32 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/elastic-package/pipelines/PR-332/runs/1/steps/160/log/?start=0">here</a></li>
<li>Description: <code>make check</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-04-20T14:52:11.217Z] Temporary service logs removed: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/tmp/service_logs
[2021-04-20T14:52:11.217Z] Done
[2021-04-20T14:52:11.217Z] + for d in test/packages/*/
[2021-04-20T14:52:11.217Z] + cd test/packages/kubernetes/
[2021-04-20T14:52:11.217Z] + elastic-package clean -v
[2021-04-20T14:52:11.217Z] 2021/04/20 14:52:11 DEBUG Enable verbose logging
[2021-04-20T14:52:11.217Z] Clean used resources
[2021-04-20T14:52:11.217Z] 2021/04/20 14:52:11 DEBUG Clean build resources
[2021-04-20T14:52:11.217Z] 2021/04/20 14:52:11 DEBUG Build directory for integration: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/src/github.com/elastic/elastic-package/build/integrations/kubernetes
[2021-04-20T14:52:11.217Z] 2021/04/20 14:52:11 DEBUG Remove directory (path: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/src/github.com/elastic/elastic-package/build/integrations/kubernetes)
[2021-04-20T14:52:11.218Z] Build resources removed: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/src/github.com/elastic/elastic-package/build/integrations/kubernetes
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Clean built packages from the development stack
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Remove folder (path: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/stack/development/kubernetes)
[2021-04-20T14:52:11.218Z] Package removed from the development stack: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/stack/development/kubernetes
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Clean all service logs
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Remove folder content (path: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/tmp/service_logs)
[2021-04-20T14:52:11.218Z] Temporary service logs removed: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/tmp/service_logs
[2021-04-20T14:52:11.218Z] Done
[2021-04-20T14:52:11.218Z] + for d in test/packages/*/
[2021-04-20T14:52:11.218Z] + cd test/packages/log/
[2021-04-20T14:52:11.218Z] + elastic-package clean -v
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Enable verbose logging
[2021-04-20T14:52:11.218Z] Clean used resources
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Clean build resources
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Build directory for integration: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/src/github.com/elastic/elastic-package/build/integrations/log
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Remove directory (path: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/src/github.com/elastic/elastic-package/build/integrations/log)
[2021-04-20T14:52:11.218Z] Build resources removed: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/src/github.com/elastic/elastic-package/build/integrations/log
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Clean built packages from the development stack
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Remove folder (path: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/stack/development/log)
[2021-04-20T14:52:11.218Z] Package removed from the development stack: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/stack/development/log
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Clean all service logs
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Remove folder content (path: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/tmp/service_logs)
[2021-04-20T14:52:11.218Z] Temporary service logs removed: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/tmp/service_logs
[2021-04-20T14:52:11.218Z] Done
[2021-04-20T14:52:11.218Z] + for d in test/packages/*/
[2021-04-20T14:52:11.218Z] + cd test/packages/multiinput/
[2021-04-20T14:52:11.218Z] + elastic-package clean -v
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Enable verbose logging
[2021-04-20T14:52:11.218Z] Clean used resources
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Clean build resources
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Build directory for integration: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/src/github.com/elastic/elastic-package/build/integrations/multiinput
[2021-04-20T14:52:11.218Z] 2021/04/20 14:52:11 DEBUG Remove directory (path: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/src/github.com/elastic/elastic-package/build/integrations/multiinput)
[2021-04-20T14:52:11.218Z] Build resources removed: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/src/github.com/elastic/elastic-package/build/integrations/multiinput
[2021-04-20T14:52:11.219Z] 2021/04/20 14:52:11 DEBUG Clean built packages from the development stack
[2021-04-20T14:52:11.219Z] 2021/04/20 14:52:11 DEBUG Remove folder (path: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/stack/development/multiinput)
[2021-04-20T14:52:11.219Z] Package removed from the development stack: /var/lib/jenkins/workspace/t-manager_elastic-package_PR-332/.elastic-package/stack/development/multiinput
[2021-04-20T14:52:11.219Z] 2021/04/20 14:52:11 DEBUG Cl [...]

2021-04-20 15:05 UTC, mtojek commented on internal/testrunner/runners/system/servicedeployer/kubernetes.go
> +	ctxt.Agent.Host.NamePrefix = "kind-control-plane"
nit: missing trailing dash or is it on purpose?

I'm not sure about implications of this change. Would you mind sharing more context? Will it affect any existing integrations

2021-04-20 15:09 UTC, mtojek requested changes
I will block this PR from merging, so that we're sure that we won't merge anything breaking here.

2021-04-20 15:09 UTC, mtojek commented on internal/testrunner/runners/system/servicedeployer/kubernetes.go
> +	ctxt.Agent.Host.NamePrefix = "kind-control-plane"
I looked into the kubectl dump for the failed build: https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-332/1/artifact/build/kubectl-dump.txt

and I see that there is a mix of `kind-control-plane` and `kind-fleet-agent-clusterscope`. I admit I'm bit lost here.

2021-04-20 16:21 UTC, ChrsMark commented
Deploying Agent using `hostNetwork` will result into a different hostname. Pod will fallback to node's name for the hostname. This will lead into having Agent registered as `kind-control-plane` (name of the host) in fleet server while the test will be waiting for `kind-fleet-agent-*` and it will stall there forever (==timeout).

2021-04-20 16:31 UTC, mtojek commented
Would you mind adding a comment in code around NodePrefix, justifying the "kind-control-plane"? I'm a bit cautious while dealing with host network and potential implications, but if there is no other option, let's do this. I undestand that it will only impact the kubernetes integration. Do you think that it won't be a problem in the future? Let's say, we would like to build the integration with istio.

2021-04-20 16:32 UTC, mtojek approved these changes
Not blocking, thank you for the explanation.

2021-04-21 07:39 UTC, ChrsMark commented
> Would you mind adding a comment in code around NodePrefix, justifying the "kind-control-plane"? I'm a bit cautious while dealing with host network and potential implications, but if there is no other option, let's do this. I undestand that it will only impact the kubernetes integration. Do you think that it won't be a problem in the future? Let's say, we would like to build the integration with istio.

We use `hostNetwork` in our actual manifests too so it shouldn't be a problem for this testing scenario since it is actually identical to the real world's case:
https://github.com/elastic/beats/blob/188345dc96876011fd397ad7fd2f721459e102d7/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L457
https://github.com/elastic/beats/blob/188345dc96876011fd397ad7fd2f721459e102d7/deploy/kubernetes/metricbeat-kubernetes.yaml#L146

I cannot think of any specific issue we can hit in the future because of this. Other k8s services/apps will be available using DNS resolution of k8s (using k8s service's name like what we do for kube-state-metrics). `hostNetwork` is also useful for autodiscovery (out of package's scope) so as to enable a k8s api watcher on node's level. 

In general, I think we are on the safe side with this ("hold my beer" 😄 ).

2021-04-21 11:42 UTC, mtojek commented
@ChrsMark I think this one is good to go now.

2021-04-21 12:03 UTC, merged