Add dependabot
elastic/elastic-package pull request #404
Opened 2021-07-06 17:26 UTC by v1v

## What

Delegate the bump automation to `dependabot`. Please read below

## Why

Simplify recurrent tasks

## Next steps

`Allow` is not supported to declare the list of dependencies to be bumped, something that is supported for some other package systems. See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#allow

The proposal is, delegate the bump automation to dependabot and for each dependency that should not be taking in consideration then:

- ignore it explicitly as stated in https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#creating-ignore-conditions-from-dependabot-ignore

2021-07-06 17:50 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package%2FPR-404/detail/PR-404/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package%2FPR-404/detail/PR-404/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package%2FPR-404/detail/PR-404/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package%2FPR-404/detail/PR-404/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://elastic-package_404.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2021-07-06T17:17:01.778Z&rangeTo=2021-07-06T17:37:01.778Z&transactionName=Ingest-manager/elastic-package/PR-{number}&transactionType=unknown&latencyAggregationType=avg&traceId=5a632445a583181d6eadb7f297a0915c&transactionId=bef74942f565c8c8)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2021-07-06T17:27:01.778+0000


* Duration: 24 min 35 sec


* Commit: 1d423dff9af7e6d6025538d311128909e26b520b



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 315  |
| Skipped      | 2 |
| Total        | 317   |


#### Trends :test_tube:


![Image of Build Times](https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-404/buildTimeGraph/png)


![Image of Tests](https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-404/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->












<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2021-07-07 09:46 UTC, mtojek requested changes
Thanks for the PR.

Could you please add another one for https://github.com/elastic/package-spec ? The dependency graph is as follows: integrations -> elastic-package -> package-spec.

If the dependabot works well for package-spec, we can enable it for elastic-package.

2021-07-07 15:21 UTC, v1v commented
https://github.com/elastic/package-spec/pull/196 has been merged, let's wait until dependabot runs and then we can move forward if we are happy with the outcome

2021-07-07 15:41 UTC, mtojek approved these changes
Looks like dependabot did a great job, let's continue this initiative.

2021-07-07 15:48 UTC, v1v commented on .github/dependabot.yml
> +  	open-pull-requests-limit: 10
```suggestion
    open-pull-requests-limit: 10
```

2021-07-07 15:49 UTC, v1v commented
I'll merge this PR without running a new build in the CI since it does nothing in the CI at all

2021-07-07 15:49 UTC, merged